create table if not exists public.device_data (
  id bigint generated by default as identity primary key,
  device_uuid text not null,
  timestamp timestamptz not null,
  record_type text not null check (record_type in ('sensor', 'camera', 'unknown')),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists device_data_timestamp_idx
  on public.device_data (timestamp desc);

create index if not exists device_data_device_uuid_timestamp_idx
  on public.device_data (device_uuid, timestamp desc);

alter table public.device_data enable row level security;

drop policy if exists "Public read device data" on public.device_data;
create policy "Public read device data"
  on public.device_data
  for select
  to anon, authenticated
  using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'device_data'
  ) then
    alter publication supabase_realtime add table public.device_data;
  end if;
end $$;
