create table if not exists public.device_data (
  id bigint generated by default as identity primary key,
  device_uuid text not null,
  timestamp timestamptz not null,
  record_type text not null check (record_type in ('sensor', 'camera', 'unknown')),
  data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists device_data_timestamp_idx
  on public.device_data (timestamp desc);

create index if not exists device_data_device_uuid_timestamp_idx
  on public.device_data (device_uuid, timestamp desc);

alter table public.device_data enable row level security;

drop policy if exists "Public read device data" on public.device_data;
create policy "Public read device data"
  on public.device_data
  for select
  to anon, authenticated
  using (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'device_data'
  ) then
    alter publication supabase_realtime add table public.device_data;
  end if;
end $$;


create table if not exists public.milesight_devices (
  device_uuid text primary key,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  record_type text,
  latest_data jsonb not null default '{}'::jsonb,
  assignment text check (
    assignment is null or assignment in (
      'code_indoor',
      'passivehouse_indoor',
      'outdoor_shared'
    )
  ),
  updated_at timestamptz not null default now()
);

create index if not exists milesight_devices_last_seen_idx
  on public.milesight_devices (last_seen_at desc);

alter table public.milesight_devices enable row level security;

-- No public RLS policy is intentionally created for milesight_devices.
-- Admin/API access uses the Supabase service-role key on the server.


create table if not exists public.webhook_events (
  id bigint generated by default as identity primary key,
  received_at timestamptz not null default now(),
  status text not null check (
    status in ('received', 'processed', 'rejected', 'ignored', 'error')
  ),
  http_status integer,
  authorized boolean,
  source_ip text,
  user_agent text,
  request_id text,
  event_count integer not null default 0,
  inserted_count integer not null default 0,
  device_uuids jsonb not null default '[]'::jsonb,
  record_types jsonb not null default '[]'::jsonb,
  message text
);

create index if not exists webhook_events_received_at_idx
  on public.webhook_events (received_at desc);

alter table public.webhook_events enable row level security;

-- No public RLS policy is intentionally created for webhook_events.
-- Logs are read only from authenticated server-side admin endpoints.
